### ISSUE TITLE
Port glnx_file_copy_at

### ISSUE THREAD

**Issue by lucab** [coreos/openat-ext#15]
This crate should grow an helper method for copying filesystem entries like `glnx_file_copy_at`, see
https://gitlab.gnome.org/GNOME/libglnx/-/blob/900caea698690b18db4f2a9cd2c3abb4f84f10b5/glnx-fdio.c#L922.

I think this would be the first method taking bit-flags, so the ticket likely needs some input from @cgwalters about how he prefers to encode/pass those.

**Comment by lucab** [comment]
Cross-reference: https://github.com/cgwalters/openat-ext/pull/16 covers the `(NOXATTR: true, OVERWRITE: true)` case out of the larger matrix of flags combinations.

**Comment by cgwalters** [comment]
Right, I'm thinking we can start with the simple case first - most times people will want (overwrite, no fsync, skip xattrs) etc.

**Comment by cgwalters** [comment]
I think we should be focusing on cap-std now.  I think actually most use cases here are covered by the new https://docs.rs/cap-std-ext/latest/cap_std_ext/dirext/trait.CapStdExtDirExt.html#tymethod.replace_file_with API - in that closure one can e.g. flush the buffer then invoke `fsync()`, and/or change ownership, add xattrs etc.
