### ISSUE TITLE
[API change] OpenatDirExt: return boolean to signal the action was performed

### ISSUE THREAD

**Issue by lucab** [coreos/openat-ext#7]
From https://github.com/cgwalters/openat-ext/pull/6#discussion_r501554424:

> [LB] should this method (and possibly a few other similar ones below) return a Result<bool> or something like that to let the caller distinguish the "action performed" and "nothing to be done" cases?

>  [CW] Hmm, yeah no harm in returning the bool.

Specifically, I'd like to get back a `true` is the optional action was performed and `false` if it wasn't.

**Comment by cgwalters** [comment]
This was done.
